### ISSUE TITLE
[Bug] Trying to connect more then 2 minecarts cause crash 

### ISSUE THREAD

**Issue by Niketats** [CammiesCorner/Cammies-Minecart-Tweaks#10]
[crash-2022-03-27_02.45.40-server.txt](https://github.com/CammiePone/Cammies-Minecart-Tweaks/files/8356531/crash-2022-03-27_02.45.40-server.txt)

**Comment by CammiePone** [comment]
It's not an issue connecting more than 2 minecarts, you can do that just fine, it has to do with the order in which you did the connections. This is a known bug, it's fixed in dev.
