### ISSUE TITLE
Minecart deal damage before it actually touches player. 

### ISSUE THREAD

**Issue by cowsha** [CammiesCorner/Cammies-Minecart-Tweaks#11]
Thats it.

**Comment by CammiePone** [comment]
Not a bug, or rather is, but not with my mod. Minecarts use really janky interpolation that Mojang has never bothered to fix. If you were to have placed a block instead of a player there, the minecart would've stopped before it ever touched the block.

**Comment by cowsha** [comment]
Sometimes just stops right in front of player or passing it and keep rolling away.
Gotcha.

**Comment by CammiePone** [comment]
Again, issue with vanilla's interpolation of minecarts. No one ever uses them though, so most people don't even know it's a problem. Isn't helped by the fact I'm making them move 5 times faster than they normally could though. Makes the issues more pronounced.
