### ISSUE TITLE
Connecting the Carts?

### ISSUE THREAD

**Issue by NealSavage** [CammiesCorner/Cammies-Minecart-Tweaks#13]
How do I connect the carts with a chain? Tried clicking one then the other, tried placing between the two (this resulted in the chain just being placed vertically like a normal chain), etc. Cannot get them to connect. I checked the config menu and it is enabled, so. What's wrong/how do I do it?

**Comment by CammiePone** [comment]
Shift right click the leading cart with the chain, then the following cart

**Comment by NealSavage** [comment]
Uhh.. so... my minecart with furnace appears to have taken my chain from me and used it as a fuel when I did this

**Comment by NealSavage** [comment]
Starting with shift right clicking the regular mine cart and then the minecart with furnace made it work, but perhaps that's a bug that should be fixed? I'll add it as its own issue report for you since technically the posted issue is fixed. Thanks for the prompt help tho!

**Comment by CammiePone** [comment]
Wont work, can tell you now. The bug you mentioned has already been fixed in Dev, just hasnt been pushed

**Comment by NealSavage** [comment]
Is this also the case with the minecart with chest? Usually does nothing but sometimes the chest cart will delete my chain.

**Comment by CammiePone** [comment]
Yea
