### ISSUE TITLE
Not going anywhere

### ISSUE THREAD

**Issue by NealSavage** [CammiesCorner/Cammies-Minecart-Tweaks#15]
Furnace with minecart attached to another cart via a chain will not go anywhere. Tried both coal and sticks as the fuel.

**Comment by CammiePone** [comment]
You most likely connected them in the wrong order. What happens when you push on either of them

**Comment by NealSavage** [comment]
Due to the bug discussed yesterday about the furnace taking the chain as fuel, I was forced to connect regular minecart then furnace. When I push the cart towards the furnace, it goes forward, slams into the furnace one, jumbles up as one cart. When I push the cart away from the furnace, the chain pops off, the two connect without the chain and it pulls furnace that way til the inertia of the push runs out. I push the furnace one first, nothing happens, regardless of which direction I push.

**Comment by CammiePone** [comment]
That's why, this isnt a bug you just did them in the wrong order.

If you dont want the chain being consumed, check if it has an nbt tag or not (you can check with F3 + H). If it does, it's doomed already. If it doesnt, _then_ you connect the furnace first

**Comment by NealSavage** [comment]
Doesn't have an NBT tag. Just says minecraft:chain. Checked the car with furnace in case that's what you meant, that's just minecraft:furnace_minecart. No NBT tag.

**Comment by UpcraftLP** [comment]
> it's doomed already.

read: place it as a block and mine it again
