### ISSUE TITLE
Does not go around corners correctly.

### ISSUE THREAD

**Issue by NealSavage** [CammiesCorner/Cammies-Minecart-Tweaks#16]
Video attached to explain cuz it would take too many words.

[cammies minecarts corner problem.zip](https://github.com/CammiePone/Cammies-Minecart-Tweaks/files/8455161/cammies.minecarts.corner.problem.zip)

**Comment by CammiePone** [comment]
Upload it to youtube ple I dont like downloading things Im gonna delete 5 seconds later

**Comment by UpcraftLP** [comment]
if you want to do a 180° turn, you need at least 2 blocks of straight rail between the curved pieces.

**Comment by NealSavage** [comment]
> 

https://youtu.be/7PTvNxuXHh8

Here you go

**Comment by CammiePone** [comment]
Yeah you need 1 extra block at least. This isnt a bug, its just not fixable without immense jank

**Comment by NealSavage** [comment]
Perhaps add that info to the description of the mod so that people(i tested as I went, so not me) don't build massive rail systems then have to change a bunch of it because they didn't know that

**Comment by CammiePone** [comment]
It's not needed. Simple trial and error can tell them that. Most people don't build such turns in large railway systems, as most large railways try to go straight for as long as possible to reduce wasted materials.

Also, it's not my job to inform people of things they should naturally test before building supermassive structures.

**Comment by NealSavage** [comment]
I mean, sure, it's not your job, but it ends up in wasted time when people like me post issues about it when you could have just put it in the description. All of the problems I've hit so far, since they are all known, and some with updates to be pushed soon, should have been in the description as they are ones that basically everyone is going to run into.

And, such turns would be used precisely to reduce wasted materials by having a shorter turn...? So, logically, this is the turn one should expect people to use....? Fixing the turn problem literally made me have to go and craft more rails, since it brought each turn up from 3 rails to 8 so, yeah...

Also, if creating it underground, it adds resource usage in terms of tool durability as you have to clear out more of the ground for more rail just for a turn. Mines are usually tight places, not a place for a sprawling turn radius.

**Comment by NealSavage** [comment]
Also, it still has a problem on one of the turns even after making it have 2 across. 
![image](https://user-images.githubusercontent.com/4138801/162533642-c993e330-2150-42a0-92e9-4935aaa6d10e.png)
Around where my cursor is is causing the chain to stretch and break off, which it should not as it is not a 180 degree turn.

**Comment by NealSavage** [comment]
> Also, it still has a problem on one of the turns even after making it have 2 across. ![image](https://user-images.githubusercontent.com/4138801/162533642-c993e330-2150-42a0-92e9-4935aaa6d10e.png) Around where my cursor is is causing the chain to stretch and break off, which it should not as it is not a 180 degree turn.

I can put this as a new issue if you'd prefer, since you put this one as closed already?

**Comment by mageowl** [comment]
This is the same issue. Simply put another rail in between the second turn and the third.
