### ISSUE TITLE
[Bug Report] Linked minecarts will break when two curves are near each other

### ISSUE THREAD

**Issue by KarlosWGeek** [CammiesCorner/Cammies-Minecart-Tweaks#17]
To replicate, build this then fuel the Minecart with Furnace.

![2022-04-08_20 07 17](https://user-images.githubusercontent.com/38844091/162545260-63e5c00c-0642-45a7-951e-6dcc75a5c1e4.png)

The **expected behavior** is that the Minecart with Chest will follow the path of the Minecart with Furnace, as it's being pulled by it.
The **actual behavior** is that the Minecart with Chest doesn't make the corner, instead it gets dragged in the opposite way by the Minecart with Furnace. The Minecart with Chest will move back and forth in the top rail, while the Minecart with Furnace will travel normally and clip through the Minecart with Chest when both are in the top rail (Minecart with Furnace will start in the back, clip through so it's in front, then the cycle repeats).

![2022-04-08_20 07 24](https://user-images.githubusercontent.com/38844091/162546505-2268943e-7b8d-4f30-acbb-f428fcb2b73e.png)

This is not caused by the Furnace Minecart's high speed. You can replicate it at a snail's pace by building the following, then holding forward while on the Minecart.

![2022-04-08_20 32 15](https://user-images.githubusercontent.com/38844091/162546459-1fd40c01-6101-41c0-a869-da1ecb68530e.png)

The Minecart will go to the bottom rail, while the Minecart with Chest remains in the top rail. Below are situations where this does (light on) and doesn't (light off) happen, regardless of the speed of either Minecart.

![2022-04-08_20 37 00](https://user-images.githubusercontent.com/38844091/162546706-298bca29-a46f-497d-a867-e504285ea542.png)

**Comment by CammiePone** [comment]
Not a bug, just a limitation unless I wanna deal with major jank, which I don't.

**Comment by NealSavage** [comment]
See what I mean, Cammie? If you're gonna pass the jank onto the users, at least warn them by putting it in the description
