### ISSUE TITLE
[bug] Attempted to push a chest minecart that was connected to two other minecarts and got this: 

### ISSUE THREAD

**Issue by SebastianDevus** [CammiesCorner/Cammies-Minecart-Tweaks#19]
[crash-2022-04-09_19.31.41-server.txt](https://github.com/CammiePone/Cammies-Minecart-Tweaks/files/8457873/crash-2022-04-09_19.31.41-server.txt)

**Comment by CammiePone** [comment]
Already fixed in dev. I should probably just push it at this point even though I'm not finished with everything I wanted for the next update
