### ISSUE TITLE
[Suggestion] Make minecarts with chest/hopper/furnace drop as combined item

### ISSUE THREAD

**Issue by Jummit** [CammiesCorner/Cammies-Minecart-Tweaks#24]
Minecarts with chests, hoppers and furnaces should drop their combined item, not as two.

This is already covered by another mod, but since this mod is called "Minecart Tweaks" I think this belongs in here.

**Comment by UpcraftLP** [comment]
This feature already exists, if you use any tool to break the minecarts.
