### ISSUE TITLE
Infinite inertia with two connected minecarts with one inbetween

### ISSUE THREAD

**Issue by Jummit** [CammiesCorner/Cammies-Minecart-Tweaks#25]
If you place three minecarts and chain the first and third one together, they will move in one direction indefinitely.
This is a problem in vanilla too, but I think the cause is different here.

![image](https://user-images.githubusercontent.com/28286961/166137998-cb691ffc-4c5f-48bb-bce6-cde31cd7d9c8.png)

**Comment by CammiePone** [comment]
Oh that's actually really funny. Unfortunately, there isnt really much of a fix that wont break other things (I know why it's happening, trust me) sooooo...
