### ISSUE TITLE
Minecarts can be chained to themselves

### ISSUE THREAD

**Issue by Jummit** [CammiesCorner/Cammies-Minecart-Tweaks#26]
It is possible to shift-right click with a chain on a minecart twice.

**Comment by UpcraftLP** [comment]
Already fixed, update the mod.

**Comment by Jummit** [comment]
Sorry, I didn't check if the problem existed in the latest version. I'll try to keep that in mind in the future. Just a heads up though; the "Featured Version" on Modrinth currently leads to 1.3 and 1.4.
