### ISSUE TITLE
Furnace minecart accelerates without fuel

### ISSUE THREAD

**Issue by Jummit** [CammiesCorner/Cammies-Minecart-Tweaks#27]
Steps to reproduce:

1. Chain a furnace minecart to another minecart
2. Push the minecarts
3. Destroy the other minecart
4. Furnace minecart accelerates and acts like it has fuel

EDIT: It seems that this is caused by the acceleration shift-right clicking the furnace minecart provides. This should not happen when chaining minecarts together.

**Comment by UpcraftLP** [comment]
Already fixed, update the mod.
