### ISSUE TITLE
Minecart Mod on Multiplayer Server

### ISSUE THREAD

**Issue by Ikcetam** [CammiesCorner/Cammies-Minecart-Tweaks#31]
Hello,
I attempting to set up a 1.18.2 multiplayer Minecraft server for me and my mates, I found this minecart mod quite interesting and I think the features demonstrated in the mod should be vanilla, but I have been struggling to get the plugin-in working. Is the plugin for the server the same as the single player file or do I need a different file. Assistance in helping me set up this mod on the server. If you could write some instructions to help that would be much appreciated. (I'm relatively new to the server space and have only run one server world in the past).
Thanks, 
Ikcetam :)

**Comment by CammiePone** [comment]
it's not a plugin. the server needs to be running on Fabric or Quilt, not Spigot or Paper, and any clients that join need to have it installed as well

**Comment by Ikcetam** [comment]
Oh, ok. Unfortunately this means we will not be able to use this mod, which is a shame as i think that many tweaks seen in this mod should be in vanilla mc. We have some friends that only have bedrock (on consoles and mobile) and we rely on gyser to play with them. Do you know of any alternatives, most minecart plugins focus on rollercoasters and thrill riders but all we want is something basic and reletavly vanilla feeling like yours. Thanks for the answer.
