### ISSUE TITLE
How do chains link?

### ISSUE THREAD

**Issue by Soggyshorts** [CammiesCorner/Cammies-Minecart-Tweaks#34]
How do I link minecarts with chains? I've tried every clicking combo I can think of. Also, how do I access a furnace cart's storage? When I click it with a stack of wood it goes, but there's no indication of how full it is.
Sorry for the noob questions

**Comment by CammiePone** [comment]
shift right click with a chain on the leading cart, then the following cart. so if you have a furnace minecart with two minecarts behind it, you start with the furnace minecart and link it to the middle minecart, then you click on the middle minecart again and link it to the last minecart

as for the furnace minecart, that's just vanilla behaviour. the game has no idea what item's in it once it's put in. it immediately gets turned into a numerical value and that's it
