### ISSUE TITLE
Server Crashing

### ISSUE THREAD

**Issue by ChiefRunnyLips** [CammiesCorner/Cammies-Minecart-Tweaks#37]
My server keeps crashing because of the Ticking entity the minecart hopper. We have a single one minecart hopper on the server collecting items for a farm. 
[crash-2022-10-14_18.10.37-server.txt](https://github.com/CammiePone/Cammies-Minecart-Tweaks/files/9790701/crash-2022-10-14_18.10.37-server.txt)
This is the crash report

**Comment by CammiePone** [comment]
fixed now by Will's PR
