### ISSUE TITLE
Not Working on 1.19.3 (Quilt)

### ISSUE THREAD

**Issue by SnowJay2005** [CammiesCorner/Cammies-Minecart-Tweaks#40]
Game works without it installed, and crashes on launch with it installed. 
https://mclo.gs/6X3A0Y2

**Comment by arvidlindeby** [comment]
Doesn't work on Fabric as well.

**Comment by midnite111** [comment]
Crashes on launch for fabric, attached a crash log

https://mclo.gs/DdTtQeC

**Comment by CammiePone** [comment]
updated it, just a heads up for y'all, any mod not marked as 1.19.3 compatible wont run on 1.19.3. 1.19.3 broke basic things so basically nothing works on it without an explicit update
