### ISSUE TITLE
[Crash] crash when boot

### ISSUE THREAD

**Issue by DanMeadWasTaken** [CammiesCorner/Cammies-Minecart-Tweaks#41]
Logs point towards something to do with moonlight api- but i am too tired rn to remember which mod is using that. here are the logs

https://mclo.gs/QdhxFmq

**Comment by UpcraftLP** [comment]
seems like there's a conflict with `highspeed-rail`, due to both mods providing the same functionality.

**Comment by DanMeadWasTaken** [comment]
Thank ya! i ended up just replacing highs-peed rail with gravel carts. which at least in my case is what i wanted to begin with but it wasn't showing up in the prism search so manually downloaded... idk, I'm tired as heck and need to just sleep
