### ISSUE TITLE
Crash when opening mod menu config

### ISSUE THREAD

**Issue by AnImpossibility** [CammiesCorner/Cammies-Minecart-Tweaks#44]
Upon clicking the mod menu config button, I was given a crash. I retried, and this seems to be consistent (for me at least).
[crash-2023-03-10_18.09.51-client.txt](https://github.com/CammiePone/Cammies-Minecart-Tweaks/files/10946783/crash-2023-03-10_18.09.51-client.txt)

**Comment by CammiePone** [comment]
can you upload the crash to something like Pastebin?

**Comment by AnImpossibility** [comment]
alright, hold on.

**Comment by AnImpossibility** [comment]
https://pastebin.com/2SDtPEi5

**Comment by CammiePone** [comment]
midnightlib 1.1.0 is 1.19.3 only

**Comment by AnImpossibility** [comment]
Edit: After removing midnightlib
I'm getting this error when I start the game..?
![image](https://user-images.githubusercontent.com/105756699/224447397-c79005b8-d8bb-4072-b4fd-d390401d40ec.png)
Edit 2: Move this to discord?
Edit 3: NEVERMIND! I didn't understand your comment and thought you meant something else. I tried again with the right version of midnightlib and it's working now. Thanks for the help!

**Comment by CammiePone** [comment]
np
