### ISSUE TITLE
Asking for permission (sorry for doing it here)

### ISSUE THREAD

**Issue by notIkibo** [CammiesCorner/Cammies-Minecart-Tweaks#45]
Heyaaa,

I really like this mod and would use it in a modpack on modrinth. I know this is usually not the place to ask for it, but I don't know where else to ask. "Tracking down" any devs discord seems even weirder to me. Maybe I'm missing a different way tho :o

**Comment by Xiribidus** [comment]
Im just going to quote lotus itself on this

![Screenshot_20230507-123433_Discord.jpg](https://user-images.githubusercontent.com/83953120/236672443-cf3af063-883d-4ed3-ad8d-b622660cc7b0.jpg)

**Comment by CammiePone** [comment]
also my Discord server is linked in the description of all my mods, feel free to drop on by if you wanna ^-^

**Comment by notIkibo** [comment]
:ooo oh yeah, I looked for a discord server, but didn't notice this big button. And I was on curseforge before and had the 1.7 version which apparently doesn't exist on modrinth (only 1.6) which is why modrinth said that I am not allowed to use it since Curseforge is Curseforge. Anyway, I'll be joining :33
![image](https://user-images.githubusercontent.com/106886638/236676819-2d431660-2c50-4e29-9379-8077baa7e297.png)
