### ISSUE TITLE
Trains longer than 2 crashing when traveling in a straight line (seemingly only on the X axis in the nether?)

### ISSUE THREAD

**Issue by kikoboy11** [CammiesCorner/Cammies-Minecart-Tweaks#46]
[crash-2023-05-14_05.05.52-server.txt](https://github.com/CammiePone/Cammies-Minecart-Tweaks/files/11471537/crash-2023-05-14_05.05.52-server.txt)

**Comment by kikoboy11** [comment]
*Crashes the server when traveling on X axis at all. Links of only 2 carts seem to work okay but linking 3 or more fails.

**Comment by traincrisis** [comment]
Same issue. But for me with works in both axis

**Comment by CammiePone** [comment]
yeah, it seems to be a weird bug and im not sure what's causing it at the moment. i havent been able to get around to modding until more recently since life events have left me drained

**Comment by CammiePone** [comment]
~~so yall wanna know the problem? im a fucking moron. i changed the name of a class, but forgot to change it in the entrypoint in the mod.json file lmao~~

wait no, that's a different problem lmao

**Comment by CammiePone** [comment]
alright, its been fixed. new version should be up on CF and Modrinth soon

idk when i'll get it moved over to Fabric atm, or when i'll rewrite some of the code. too tired right now to do it
