### ISSUE TITLE
1.19.4 & 1.20

### ISSUE THREAD

**Issue by terminal-cs** [CammiesCorner/Cammies-Minecart-Tweaks#48]
Hello,

I request that this mod be updated to the latest versions. If possible, it would be great if a 1.19.4 version could be made aswell because that's what i'm stuck on at the moment, and the 1.19.3 version of this mod crashes in 1.19.4.

Thanks

**Comment by CammiePone** [comment]
![Screenshot_20230721-101834_Discord](https://github.com/CammiePone/Cammies-Minecart-Tweaks/assets/16853086/a1a89ae5-a184-4bec-8e1f-7880327f03e8)

**Comment by terminal-cs** [comment]
🐟🐟🐟
