### ISSUE TITLE
[Request] Slow down minecarts when ascending and turning.

### ISSUE THREAD

**Issue by Vaixell** [CammiesCorner/Cammies-Minecart-Tweaks#5]
'Ello!

Minecarts can collide with the block next to an ascending rail when going over 10m/s, causing the minecart to bounce back and making higher speeds unreliable. This also breaks linked minecarts.

Could you make minecarts slow down before ascending? Other minecart mods are doing it, too. They also limit the speed in turns to 10m/s to prevent derailing although even long chains of over 20 minecarts seem to be stable in turns at 12m/s in my testing.

**Comment by CammiePone** [comment]
Already the case, it's just a pain to slow down the carts.
