### ISSUE TITLE
[Crash] [1.19.2]

### ISSUE THREAD

**Issue by Frank18040131238** [CammiesCorner/Cammies-Minecart-Tweaks#51]
I've noticed a bug: when the minecart hit an entity, and the entity was killed because of that, the game would crash, but if the entity wasn't killed, then the game wouldn't crash. 
I uploaded the crash report.(It's a crash report of my server)

[crash-2024-04-13_21.50.46-server.txt](https://github.com/CammiePone/Cammies-Minecart-Tweaks/files/14970799/crash-2024-04-13_21.50.46-server.txt)

(PS: I'm Chinese and my English is terrible. I hope you can understand what I mean.😂)

**Comment by CammiePone** [comment]
oh yeah. i forgot about this bug. it'll be fixed in the next update (hopefully). thank you for bringing it back to my attention!
