### ISSUE TITLE
Pathing on zig-zag track is broken

### ISSUE THREAD

**Issue by hibiii** [CammiesCorner/Cammies-Minecart-Tweaks#7]
Tracks for farm collection systems are usually placed in a zig-zag fashion, where a minecart does a 180° turn as soon as it hits the edge of the farm, and continues until it covers the full width of a farm.

Minecarts tend to confuse which straight line they're running in, causing it to eventually go backwards. Additionally, minecarts may also derail on a turn, but this does seem like a documented feature. Even setting the maximum cornering speed to a ludicrous 5000 m/s doesn't mitigate the derailing.

also nice commit messages

**Comment by CammiePone** [comment]
Higher speeds will cause them to derail easier. Lower speeds will keep them on the rails.

As for tight 180 degree turns, it's known and is basically unavoidable.
